name = "photo"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"

[site]
bucket = "./public"

[build]
command = "yarn build"

# [dev]
# local_protocol = "https"

services = [{ binding = "CONTENT", service = "content-manager" }]
