name = "photo"
main = "./build/index.js"
compatibility_date = "2023-04-20"

workers_dev = false
services = [{ binding = "CONTENT", service = "content-manager" }]

[site]
bucket = "./public"

[build]
command = "yarn build"

# [dev]
# local_protocol = "https"
