name = "dev-connorbray-net"
main = "./server.js"
compatibility_date = "2023-04-20"

r2_buckets = [
    { binding = "CONTENT", bucket_name = "content", preview_bucket_name = "content-dev" },
]

[site]
bucket = "./build/client"

[build]
command = "yarn build"

[[routes]]
pattern = "dev.connorbray.net"
custom_domain = true
