name = "connorbray-net"
main = "./server.js"
compatibility_date = "2023-04-20"

r2_buckets = [
  { binding = "CONTENT", bucket_name = "content", preview_bucket_name = "content-dev" },
]

kv_namespaces = [{ binding = "KV", id = "fed94582e0984bf4870847f671c891b6" }]

[site]
bucket = "./build/client"

[build]
command = "yarn build"

[[routes]]
pattern = "connorbray.net"
custom_domain = true

[[routes]]
pattern = "www.connorbray.net"
custom_domain = true
