// Generated by Wrangler on Wed Aug 28 2024 22:27:15 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
	KV: KVNamespace;
	DATABASE_ENDPOINT: "https://us-east-1.aws.data.mongodb-api.com/app/data-mmwij/endpoint/data/v1";
	MONGO_API_KEY: string;
	CONTENT: R2Bucket;
}
