// Generated by Wrangler on Thu Aug 22 2024 15:33:00 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
	KV: KVNamespace;
	DATABASE_ENDPOINT: "https://us-east-1.aws.data.mongodb-api.com/app/data-mmwij/endpoint/data/v1";
	MONGO_API_KEY: string;
	CONTENT: R2Bucket;
}
