name = "admin-dashboard"
main = "./server.js"
compatibility_date = "2023-05-18"

r2_buckets = [
  { binding = "CONTENT", bucket_name = "content", preview_bucket_name="content-preview" }
]

kv_namespaces = [
  { binding = "KV", id = "fed94582e0984bf4870847f671c891b6" }
]

[site]
bucket = "./build/client"

[build]
command = "yarn build"

[vars]
DATABASE_ENDPOINT = "https://us-east-1.aws.data.mongodb-api.com/app/data-mmwij/endpoint/data/v1"

[[routes]]
pattern = "admin.connorbray.net"
custom_domain = true
