name = "api"
main = "src/index.ts"
compatibility_date = "2024-03-12"

routes = [
	{ pattern = "api.connorbray.net", custom_domain = true }
]

[vars]
DATABASE_ENDPOINT = "https://us-east-1.aws.data.mongodb-api.com/app/data-mmwij/endpoint/data/v1"