name: 'Update Lines of Code'

on:
  push:
    branches:
      - main

env:
  DOT_ENV: ${{secrets.CLOC_DOT_ENV}}

jobs:
  lines_of_code:
    name: 'Update Lines of Code'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2
      - name: Install cloc
        run: sudo apt-get install -y cloc
      - name: Install node
        run: sudo apt-get install -y nodejs
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: python -m pip install --upgrade pip python-dotenv requests
      - name: Fetch backend configuration
        id: backend
        run: echo "$DOT_ENV" > .env
      - name: Run the script
        working-directory: ./scripts/python
        run: python write_cloc.py
